Repository OpenAWE-Project/OpenAWE, pull requests merged in 2021-07, with the labels that each got.

#6 Crash game in init if no .rmdp files are found
  src/game.cpp
Labels: enhancement

#7 Add build and run instructions for Linux to readme
  README.md
Labels: documentation

#18 Add missing #include in theora.cpp
  src/video/codecs/theora.cpp
Labels: bug
